// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tozxtcvgroiqeckdvifz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvenh0Y3Zncm9pcWVja2R2aWZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjUxMjYsImV4cCI6MjA2NzA0MTEyNn0.9M-m4Ebi7r0kLf5BuuWwKQHXcZVQJzhlPfRilyW_U_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});